on:
  workflow_call:

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
